/** Auto-generated by apply-next-dev-cache-fix.mjs */
/** Backup created at: next.config.js.bak */

/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack(config, { dev }) {
    /* FISCALZEN_DEV_CACHE_FIX */
    if (dev) {
      config.cache = false;
    }
    return config;
  },
};

export default nextConfig;
