/** Auto-generated by apply-next-dev-cache-fix.mjs */
/** Backup created at: next.config.js.bak */

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Standalone output só em Linux/Docker (Windows não suporta symlinks sem admin)
  output: process.platform === 'win32' ? undefined : 'standalone',
  webpack(config, { dev }) {
    /* FISCALZEN_DEV_CACHE_FIX */
    if (dev) {
      config.cache = false;
    }
    return config;
  },
};

export default nextConfig;
