import {
  NFE_DISTDFE_ENDPOINTS,
  NFE_RECEPCAO_EVENTO_ENDPOINTS,
  NFE_CONSULTA_PROTOCOLO_ENDPOINTS,
  CTE_DISTDFE_ENDPOINTS,
  CTE_RECEPCAO_EVENTO_ENDPOINTS,
  MDFE_DISTDFE_ENDPOINTS,
  MDFE_RECEPCAO_EVENTO_ENDPOINTS,
  UF_CODES as UF_CODES_MAP,
} from './constants/endpoints';

export const UF_CODES = UF_CODES_MAP;

export const SEFAZ_URLS = {
  NFE: {
    DISTDFE: NFE_DISTDFE_ENDPOINTS,
    MANIFESTACAO: NFE_RECEPCAO_EVENTO_ENDPOINTS,
    CONSULTA: NFE_CONSULTA_PROTOCOLO_ENDPOINTS,
  },
  CTE: {
    DISTDFE: CTE_DISTDFE_ENDPOINTS,
    MANIFESTACAO: CTE_RECEPCAO_EVENTO_ENDPOINTS,
  },
  MDFE: {
    DISTDFE: MDFE_DISTDFE_ENDPOINTS,
    MANIFESTACAO: MDFE_RECEPCAO_EVENTO_ENDPOINTS,
  },
};

export const DIST_DFE_SCHEMAS = {
  NFE: 'resNFe_v1.01.xsd',
  CTE: 'procCTe_v4.00.xsd',
  MDFE: 'resMDFe_v3.00.xsd',
};

export const SEFAZ_STATUS = {
  AUTORIZADO: '100',
  CANCELADO: '101',
  INUTILIZADO: '102',
  LOTE_RECEBIDO: '103',
  LOTE_PROCESSADO: '104',
  LOTE_EM_PROCESSAMENTO: '105',
  SERVICO_EM_OPERACAO: '107',
  USO_DENEGADO: '110',
  CONSULTA_CADASTRO_COM_SUCESSO: '111',
  CONSULTA_CADASTRO_COM_ERRO: '112',
  LOTE_EVENTO_PROCESSADO: '128',
  EVENTO_REGISTRADO: '135',
  EVENTO_REGISTRADO_NAO_VINCULADO: '136',
  NENHUM_DOC_LOCALIZADO: '137',
  DOC_LOCALIZADO: '138',
  CONSUMO_INDEVIDO: '656',
} as const;